// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file findnmeet/ai/v1/parse_search_query_request.proto (package findnmeet.ai.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Uuid } from "../../shared/v1/uuid_pb";
import { file_findnmeet_shared_v1_uuid } from "../../shared/v1/uuid_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file findnmeet/ai/v1/parse_search_query_request.proto.
 */
export const file_findnmeet_ai_v1_parse_search_query_request: GenFile = /*@__PURE__*/
  fileDesc("CjBmaW5kbm1lZXQvYWkvdjEvcGFyc2Vfc2VhcmNoX3F1ZXJ5X3JlcXVlc3QucHJvdG8SD2ZpbmRubWVldC5haS52MSJUChdQYXJzZVNlYXJjaFF1ZXJ5UmVxdWVzdBIqCgd1c2VyX2lkGAEgASgLMhkuZmluZG5tZWV0LnNoYXJlZC52MS5VdWlkEg0KBXF1ZXJ5GAIgASgJYgZwcm90bzM", [file_findnmeet_shared_v1_uuid]);

/**
 * @generated from message findnmeet.ai.v1.ParseSearchQueryRequest
 */
export type ParseSearchQueryRequest = Message<"findnmeet.ai.v1.ParseSearchQueryRequest"> & {
  /**
   * @generated from field: findnmeet.shared.v1.Uuid user_id = 1;
   */
  userId?: Uuid | undefined;

  /**
   * @generated from field: string query = 2;
   */
  query: string;
};

/**
 * Describes the message findnmeet.ai.v1.ParseSearchQueryRequest.
 * Use `create(ParseSearchQueryRequestSchema)` to create a new message.
 */
export const ParseSearchQueryRequestSchema: GenMessage<ParseSearchQueryRequest> = /*@__PURE__*/
  messageDesc(file_findnmeet_ai_v1_parse_search_query_request, 0);

