// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file findnmeet/ai/v1/parse_search_query_status.proto (package findnmeet.ai.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file findnmeet/ai/v1/parse_search_query_status.proto.
 */
export const file_findnmeet_ai_v1_parse_search_query_status: GenFile = /*@__PURE__*/
  fileDesc("Ci9maW5kbm1lZXQvYWkvdjEvcGFyc2Vfc2VhcmNoX3F1ZXJ5X3N0YXR1cy5wcm90bxIPZmluZG5tZWV0LmFpLnYxKpwBChZQYXJzZVNlYXJjaFF1ZXJ5U3RhdHVzEikKJVBBUlNFX1NFQVJDSF9RVUVSWV9TVEFUVVNfVU5TUEVDSUZJRUQQABIkCiBQQVJTRV9TRUFSQ0hfUVVFUllfU1RBVFVTX1BBUlNFRBABEjEKLVBBUlNFX1NFQVJDSF9RVUVSWV9TVEFUVVNfTkVFRFNfQ0xBUklGSUNBVElPThACYgZwcm90bzM");

/**
 * @generated from enum findnmeet.ai.v1.ParseSearchQueryStatus
 */
export enum ParseSearchQueryStatus {
  /**
   * @generated from enum value: PARSE_SEARCH_QUERY_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PARSE_SEARCH_QUERY_STATUS_PARSED = 1;
   */
  PARSED = 1,

  /**
   * @generated from enum value: PARSE_SEARCH_QUERY_STATUS_NEEDS_CLARIFICATION = 2;
   */
  NEEDS_CLARIFICATION = 2,
}

/**
 * Describes the enum findnmeet.ai.v1.ParseSearchQueryStatus.
 */
export const ParseSearchQueryStatusSchema: GenEnum<ParseSearchQueryStatus> = /*@__PURE__*/
  enumDesc(file_findnmeet_ai_v1_parse_search_query_status, 0);

