// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file findnmeet/ai/v1/parse_search_query_response.proto (package findnmeet.ai.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ParseSearchQueryStatus } from "./parse_search_query_status_pb";
import { file_findnmeet_ai_v1_parse_search_query_status } from "./parse_search_query_status_pb";
import type { SearchCriteria } from "../../search/v1/search_criteria_pb";
import { file_findnmeet_search_v1_search_criteria } from "../../search/v1/search_criteria_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file findnmeet/ai/v1/parse_search_query_response.proto.
 */
export const file_findnmeet_ai_v1_parse_search_query_response: GenFile = /*@__PURE__*/
  fileDesc("CjFmaW5kbm1lZXQvYWkvdjEvcGFyc2Vfc2VhcmNoX3F1ZXJ5X3Jlc3BvbnNlLnByb3RvEg9maW5kbm1lZXQuYWkudjEimwEKGFBhcnNlU2VhcmNoUXVlcnlSZXNwb25zZRI3CgZzdGF0dXMYASABKA4yJy5maW5kbm1lZXQuYWkudjEuUGFyc2VTZWFyY2hRdWVyeVN0YXR1cxIPCgdtZXNzYWdlGAIgASgJEjUKCGNyaXRlcmlhGAMgASgLMiMuZmluZG5tZWV0LnNlYXJjaC52MS5TZWFyY2hDcml0ZXJpYWIGcHJvdG8z", [file_findnmeet_ai_v1_parse_search_query_status, file_findnmeet_search_v1_search_criteria]);

/**
 * @generated from message findnmeet.ai.v1.ParseSearchQueryResponse
 */
export type ParseSearchQueryResponse = Message<"findnmeet.ai.v1.ParseSearchQueryResponse"> & {
  /**
   * @generated from field: findnmeet.ai.v1.ParseSearchQueryStatus status = 1;
   */
  status: ParseSearchQueryStatus;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: findnmeet.search.v1.SearchCriteria criteria = 3;
   */
  criteria?: SearchCriteria | undefined;
};

/**
 * Describes the message findnmeet.ai.v1.ParseSearchQueryResponse.
 * Use `create(ParseSearchQueryResponseSchema)` to create a new message.
 */
export const ParseSearchQueryResponseSchema: GenMessage<ParseSearchQueryResponse> = /*@__PURE__*/
  messageDesc(file_findnmeet_ai_v1_parse_search_query_response, 0);

