// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file findnmeet/ai/v1/service.proto (package findnmeet.ai.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ParseSearchQueryRequestSchema } from "./parse_search_query_request_pb";
import { file_findnmeet_ai_v1_parse_search_query_request } from "./parse_search_query_request_pb";
import type { ParseSearchQueryResponseSchema } from "./parse_search_query_response_pb";
import { file_findnmeet_ai_v1_parse_search_query_response } from "./parse_search_query_response_pb";

/**
 * Describes the file findnmeet/ai/v1/service.proto.
 */
export const file_findnmeet_ai_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1maW5kbm1lZXQvYWkvdjEvc2VydmljZS5wcm90bxIPZmluZG5tZWV0LmFpLnYxMnQKCUFpU2VydmljZRJnChBQYXJzZVNlYXJjaFF1ZXJ5EiguZmluZG5tZWV0LmFpLnYxLlBhcnNlU2VhcmNoUXVlcnlSZXF1ZXN0GikuZmluZG5tZWV0LmFpLnYxLlBhcnNlU2VhcmNoUXVlcnlSZXNwb25zZWIGcHJvdG8z", [file_findnmeet_ai_v1_parse_search_query_request, file_findnmeet_ai_v1_parse_search_query_response]);

/**
 * @generated from service findnmeet.ai.v1.AiService
 */
export const AiService: GenService<{
  /**
   * @generated from rpc findnmeet.ai.v1.AiService.ParseSearchQuery
   */
  parseSearchQuery: {
    methodKind: "unary";
    input: typeof ParseSearchQueryRequestSchema;
    output: typeof ParseSearchQueryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_findnmeet_ai_v1_service, 0);

